@startuml
cloud stripe

package "Docker Compose"{
 package "Docker - App"{
  component "Next Js"
 }
 database PostgreSQL
 package "Docker - Api" {
  component "Fast Api"
 }
}


package Cancela{
 component "Raspberry Pi 3"{
  component "Fast Api Server"
  component "Detecção de Placas" 
  component OCR
 }
 component Motor
 component Camera
}

package Estacionamento{
 component ESP32
 component "Hc-sr04 1"
 component "Hc-sr04 .."
 component "Hc-sr04 N"
}

"Fast Api" -> stripe 
"Next Js" <--> "Fast Api"
PostgreSQL <-- "Fast Api"
"Fast Api" <--> "Fast Api Server"
"Fast Api" <--- ESP32

"Fast Api Server" --> Motor
"Detecção de Placas" -> Camera
"Detecção de Placas" --> OCR
OCR --> "Fast Api Server"

ESP32 --> "Hc-sr04 1"
ESP32 --> "Hc-sr04 .."
ESP32 --> "Hc-sr04 N"
@enduml