@startuml
cloud stripe


package "Aplicação web"{
 package "Oracle"{
  component "Next Js"
  database PostgreSQL
  component "Fast Api"
 }
}

package Cancela{
 component "Raspberry Pi 3"{
  component "Detecção de Placas" 
  component OCR
 }
 component Motor
 component Camera
}

package Estacionamento{
 component ESP32
 component "Hc-sr04 1"
 component "Hc-sr04 N"
}

"Fast Api" -> stripe 
"Next Js" <--> "Fast Api"
PostgreSQL <-- "Fast Api"
"Fast Api" <--> "Raspberry Pi 3"
"Fast Api" <--- ESP32

"Raspberry Pi 3" --> Motor
"Detecção de Placas" -> Camera
"Detecção de Placas" --> OCR

ESP32 -->  "Hc-sr04 1"
ESP32 --> "Hc-sr04 N"
@enduml
