@startuml
participant Cancela as catraca
boundary    Aplicação as app
control     ControlerUsuario as controler
entity      EntidadeUsuario as user
database    Banco as bd


alt successful

catraca -> app ++ : <<URL>> GET/usuario?placa=%
app -> controler ++: verficaPlaca(placa)
controler-> user ++: verficaPlaca(placa)
user-> bd ++: SELECT Usuário

bd--> user: 200 success
user--> controler: 200 success
controler--> app: 200 success
app --> catraca: 200 success

else unauthorized
user--> controler: 403 unauthorized
controler--> user: usuarioTemporario(placa)
user-> bd: INSERT Usuário
bd--> user: 201 success
user--> controler: 201 success
controler--> app: 201 success
app --> catraca: 201 success

else error
bd--> user --: 500 error
user--> controler--: 500 error
controler--> app --: 500 error
app --> catraca --: 500 error

end
 
@enduml
