@startuml
participant Cancela as catraca
boundary    Aplicação as app
control     ControlerPagamento as controler
entity      EntidadeUsuario as user
database    Banco as bd
boundary    PaymentGateway as pagamento

catraca -> app ++ : <<URL>> GET/paga?placa=%
app -> controler ++: paga(placa)
controler-> user ++: paga(placa)
alt successful
user-> bd ++: SELECT estaciona
bd--> user: 200 success
user--> controler: 200 success

controler--> controler: verificaValor(valor)
alt successful
controler-> pagamento++ : <<URL>> POST/payment?creditCard=%

pagamento--> controler: 200 success
controler--> app: 200 success
app --> catraca: 200 success


else usuarioTemporario
controler--> app: 202 success
app --> catraca: 202 success

end

else error
pagamento--> controler --: 500 error
controler--> app --: 500 error
app --> catraca --: 500 error

end
 
@enduml
